"""
ppt_renderer/components/footer_renderer.py
==========================================
Footer component renderer.

Draws the footer rule, source note, date, and slide number using the
normalized footer region.
"""

from __future__ import annotations

from datetime import date
from typing import Any

from pptx.enum.shapes import MSO_AUTO_SHAPE_TYPE
from pptx.enum.text import PP_ALIGN

from ppt_renderer.components.coordinates import convert_height, convert_width, convert_x, convert_y
from backend.design_system import design_language
from backend.design_system.theme_loader import get_current_theme


def render_footer(
    footer_spec,
    presentation,
    slide,
    content: dict[str, Any],
    slide_number: int,
    *,
    pattern_id: str | None = None,
) -> None:
    """Render the slide footer anchored to the bottom of the slide."""
    theme = get_current_theme()
    spacing = design_language.get_footer_spacing(pattern_id=pattern_id)
    note_area = footer_spec.note_area or {}
    rule_y = 1.0 - footer_spec.height
    text_y = rule_y + spacing.get("text_offset", 0.01)

    rule_left = convert_x(0.05, presentation)
    rule_top = convert_y(rule_y, presentation)
    rule_width = convert_width(0.9, presentation)
    rule_height = convert_height(spacing.get("rule_height", 0.005), presentation)

    rule = slide.shapes.add_shape(
        MSO_AUTO_SHAPE_TYPE.RECTANGLE,
        rule_left,
        rule_top,
        rule_width,
        rule_height,
    )
    rule.fill.solid()
    rule.fill.fore_color.rgb = theme.color("border")
    rule.line.fill.background()

    # Source / note area
    note_text = "Generated by EY AI Pitch Prototype"
    if note_area:
        left = convert_x(note_area.get("x", 0.05), presentation)
        width = convert_width(note_area.get("width", 0.45), presentation)
        height = convert_height(note_area.get("height", 0.05), presentation)
    else:
        left = convert_x(0.05, presentation)
        width = convert_width(0.45, presentation)
        height = convert_height(0.05, presentation)
    top = convert_y(text_y, presentation)

    note_box = slide.shapes.add_textbox(left, top, width, height)
    note_p = note_box.text_frame.paragraphs[0]
    note_p.text = note_text
    _format_footer(note_p, align=PP_ALIGN.LEFT)

    # Date
    date_left = convert_x(0.40, presentation)
    date_width = convert_width(0.20, presentation)
    date_box = slide.shapes.add_textbox(date_left, top, date_width, height)
    date_p = date_box.text_frame.paragraphs[0]
    date_p.text = date.today().strftime("%d %b %Y")
    _format_footer(date_p, align=PP_ALIGN.CENTER)

    # Slide number
    number_left = convert_x(0.80, presentation)
    number_width = convert_width(0.15, presentation)
    number_box = slide.shapes.add_textbox(number_left, top, number_width, height)
    number_p = number_box.text_frame.paragraphs[0]
    number_p.text = f"Slide {slide_number}"
    _format_footer(number_p, align=PP_ALIGN.RIGHT)


def _format_footer(paragraph, align) -> None:
    theme = get_current_theme()
    paragraph.alignment = align
    paragraph.font.name = theme.font("body")
    paragraph.font.size = theme.size("footer")
    paragraph.font.color.rgb = theme.color("mid_grey")
